In [1]:
import mne
import json
import os
import ddUtils

In [2]:
dataDir = os.path.join("raw","practice")
paths = [os.path.join(dataDir,f"practice{i}.json") for i in range(1,11+1)]

In [3]:
subjEpochs = []
for jsonPath in paths:
    with open(jsonPath, "r") as r: data = json.load(r)
    subjEpochs.append(ddUtils.contigEpochs(data, 22))
epochs = mne.concatenate_epochs([epoch for epoch in subjEpochs if len(epoch) > 0])

[[ 995.23809524  854.21245421  848.16849817  831.64835165]
 [ 994.02930403  856.22710623  847.36263736  848.57142857]
 [1000.87912088  853.003663    848.57142857  863.07692308]
 ...
 [ 855.82417582  828.42490842  815.53113553  859.85347985]
 [ 850.98901099  831.64835165  809.89010989  861.06227106]
 [ 849.78021978  840.10989011  814.32234432  858.64468864]]
10 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
0 bad epochs dropped


Obtaining 10 epochs


[[857.03296703 852.6007326  859.85347985 846.55677656]
 [847.36263736 848.97435897 857.03296703 848.57142857]
 [837.69230769 848.97435897 858.24175824 833.66300366]
 ...
 [850.18315018 850.18315018 854.61538462 850.18315018]
 [850.18315018 850.18315018 854.61538462 850.18315018]
 [850.18315018 850.18315018 854.61538462 850.18315018]]
10 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
0 bad epochs dropped


Obtaining 10 epochs


[[824.7985348  859.45054945 865.49450549 836.88644689]
 [837.28937729 858.64468864 871.13553114 842.52747253]
 [835.67765568 857.83882784 867.50915751 846.55677656]
 ...
 [841.72161172 852.6007326  851.79487179 846.15384615]
 [846.95970696 857.03296703 851.79487179 854.21245421]
 [841.72161172 857.83882784 857.43589744 864.68864469]]
10 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
0 bad epochs dropped


Obtaining 10 epochs


[[788.53479853 853.40659341 819.15750916 861.06227106]
 [802.63736264 859.04761905 826.41025641 863.47985348]
 [805.86080586 865.8974359  828.82783883 871.13553114]
 ...
 [853.40659341 855.01831502 847.76556777 839.3040293 ]
 [853.40659341 855.01831502 847.76556777 839.3040293 ]
 [853.40659341 855.01831502 847.76556777 839.3040293 ]]
10 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
0 bad epochs dropped


Obtaining 10 epochs


[[868.31501832 849.78021978 853.40659341 870.73260073]
 [840.10989011 852.1978022  851.79487179 861.46520147]
 [832.45421245 853.40659341 853.003663   856.63003663]
 ...
 [851.79487179  22.56410256 843.73626374 831.64835165]
 [848.16849817  22.56410256 844.94505495 846.15384615]
 [858.64468864  22.56410256 842.52747253 847.36263736]]
10 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
0 bad epochs dropped


Obtaining 10 epochs


[[866.7032967  868.71794872 864.28571429 829.23076923]
 [856.22710623 870.73260073 863.47985348 850.98901099]
 [851.79487179 867.50915751 865.49450549 865.49450549]
 ...
 [833.26007326 844.13919414 827.21611722 852.6007326 ]
 [842.93040293 845.75091575 827.21611722 832.45421245]
 [839.70695971 845.34798535 830.43956044 840.51282051]]
10 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
0 bad epochs dropped


Obtaining 10 epochs


[[820.76923077 772.82051282 880.80586081 884.83516484]
 [817.54578755 776.84981685 871.13553114 904.17582418]
 [809.48717949 749.04761905 867.50915751 911.42857143]
 ...
 [867.91208791 947.28937729 809.89010989 872.34432234]
 [867.91208791 947.28937729 809.89010989 872.34432234]
 [867.91208791 947.28937729 809.89010989 872.34432234]]
10 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
0 bad epochs dropped


Obtaining 10 epochs


[[894.50549451 864.28571429 860.65934066 879.5970696 ]
 [853.003663   864.28571429 866.7032967  898.13186813]
 [849.78021978 862.27106227 872.74725275 902.56410256]
 ...
 [836.48351648 849.78021978 830.84249084 834.87179487]
 [831.24542125 848.16849817 834.87179487 837.28937729]
 [834.46886447 845.34798535 838.4981685  831.24542125]]
10 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
0 bad epochs dropped


Obtaining 10 epochs


[[724.46886447 784.90842491 848.16849817 718.42490842]
 [732.52747253 792.16117216 852.1978022  733.73626374]
 [739.78021978 794.98168498 865.09157509 747.43589744]
 ...
 [838.9010989  841.72161172 853.80952381 847.76556777]
 [838.9010989  841.72161172 853.80952381 847.76556777]
 [838.9010989  841.72161172 853.80952381 847.76556777]]
10 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
0 bad epochs dropped


Obtaining 10 epochs


[[788.53479853 868.31501832 867.10622711 904.17582418]
 [763.15018315 871.53846154 863.07692308 925.93406593]
 [688.20512821 856.22710623 852.6007326  924.32234432]
 ...
 [867.10622711 836.88644689 844.54212454 865.8974359 ]
 [867.10622711 836.88644689 844.54212454 865.8974359 ]
 [867.10622711 836.88644689 844.54212454 865.8974359 ]]
10 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
0 bad epochs dropped


Obtaining 10 epochs


[[ 697.47252747  550.80586081 1650.          684.98168498]
 [ 689.81684982  462.56410256 1650.          656.37362637]
 [ 691.42857143  660.80586081 1650.          644.28571429]
 ...
 [ 830.84249084   22.56410256  547.98534799  832.45421245]
 [ 833.26007326   22.56410256  529.45054945  840.91575092]
 [ 832.05128205   22.56410256  438.79120879  843.33333333]]
10 matching events found
No baseline correction applied
Not setting metadata
0 projection items activated
0 bad epochs dropped
110 matching events found
No baseline correction applied
Not setting metadata
0 bad epochs dropped


Obtaining 10 epochs


In [ ]:
%matplotlib inline
epochs.plot_image()

In [17]:
import numpy as np
import matplotlib.pyplot as plt
def plotOneEpoch(epoch):
    eegArray = epoch * 1e6
    time = np.arange(eegArray.shape[-1]) / 22
    for row in eegArray:
        plt.plot(time, row)
        #plt.xticks(time)
    plt.show()

In [ ]:
for epoch in epochs[:10]:
    plotOneEpoch(epoch)
    print(type(epoch))

In [ ]:
for epoch in epochs[50:60]:
    plotOneEpoch(epoch)